"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import type {Session} from "@supabase/supabase-js";
import {BarChart3,BookOpen,ChevronRight,CreditCard,LayoutDashboard,LogOut,Moon,Pencil,Plus,Search,Settings,Sun,Trash2,TrendingUp,Waves,X} from "lucide-react";
import {AuthScreen} from "@/components/AuthScreen";
import {TradeModal} from "@/components/TradeModal";
import {AccountModal} from "@/components/AccountModal";
import {getSupabase} from "@/lib/supabase";
import type {AccountDraft,Trade,TradeDraft,TradingAccount} from "@/lib/types";

type View="dashboard"|"journal"|"accounts"|"analytics"|"settings";
const money=(n:number,c="GBP")=>new Intl.NumberFormat("en-GB",{style:"currency",currency:c,maximumFractionDigits:2}).format(n||0);

export default function Home(){
 const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
 const [trades,setTrades]=useState<Trade[]>([]),[accounts,setAccounts]=useState<TradingAccount[]>([]),[view,setView]=useState<View>("dashboard");
 const [tradeOpen,setTradeOpen]=useState(false),[editingTrade,setEditingTrade]=useState<Trade|null>(null),[accountOpen,setAccountOpen]=useState(false),[editingAccount,setEditingAccount]=useState<TradingAccount|null>(null);
 const [theme,setTheme]=useState<"light"|"dark">("light"),[range,setRange]=useState("30d"),[accountFilter,setAccountFilter]=useState("all");
 const [from,setFrom]=useState(()=>new Date(Date.now()-30*86400000).toISOString().slice(0,10)),[to,setTo]=useState(()=>new Date().toISOString().slice(0,10));
 const [search,setSearch]=useState(""),[resultFilter,setResultFilter]=useState("all"),[selected,setSelected]=useState<Trade|null>(null);
 useEffect(()=>{const t=(localStorage.getItem("tradesea-theme") as "light"|"dark"|null)||("matchMedia" in window&&matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light");setTheme(t);document.documentElement.dataset.theme=t;const s=getSupabase();s.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)});const {data}=s.auth.onAuthStateChange((_e,v)=>setSession(v));return()=>data.subscription.unsubscribe()},[]);
 const load=useCallback(async()=>{if(!session)return;const s=getSupabase();const [{data:t,error:te},{data:a,error:ae}]=await Promise.all([s.from("trades").select("*").order("trade_date",{ascending:false}).order("created_at",{ascending:false}),s.from("trading_accounts").select("*").order("created_at",{ascending:true})]);if(te||ae)setError((te||ae)?.message||"Could not load data");else{setTrades((t||[]) as Trade[]);setAccounts((a||[]) as TradingAccount[])}},[session]);
 useEffect(()=>{if(session)load();else{setTrades([]);setAccounts([])}},[session,load]);
 useEffect(()=>{if(!session)return;const s=getSupabase();const ch=s.channel(`tradesea-${session.user.id}`).on("postgres_changes",{event:"*",schema:"public",table:"trades",filter:`user_id=eq.${session.user.id}`},load).on("postgres_changes",{event:"*",schema:"public",table:"trading_accounts",filter:`user_id=eq.${session.user.id}`},load).subscribe();return()=>{s.removeChannel(ch)}},[session,load]);
 function preset(v:string){setRange(v);const now=new Date();let d=new Date(now);if(v==="7d")d.setDate(now.getDate()-7);else if(v==="30d")d.setDate(now.getDate()-30);else if(v==="90d")d.setDate(now.getDate()-90);else if(v==="ytd")d=new Date(now.getFullYear(),0,1);else if(v==="all")d=new Date("2020-01-01");if(v!=="custom"){setFrom(d.toISOString().slice(0,10));setTo(now.toISOString().slice(0,10))}}
 const visible=useMemo(()=>trades.filter(t=>t.trade_date>=from&&t.trade_date<=to&&(accountFilter==="all"||t.account_id===accountFilter)),[trades,from,to,accountFilter]);
 const journal=useMemo(()=>trades.filter(t=>(accountFilter==="all"||t.account_id===accountFilter)&&(resultFilter==="all"||t.result===resultFilter)&&(!search||[t.instrument,t.account,t.setup,t.session,t.emotion,t.notes].some(x=>(x||"").toLowerCase().includes(search.toLowerCase())))),[trades,accountFilter,resultFilter,search]);
 const stats=useMemo(()=>calcStats(visible),[visible]);
 async function uploadScreenshot(file:File){if(!session)throw Error("Sign in first");const ext=file.name.split(".").pop()||"jpg",path=`${session.user.id}/${crypto.randomUUID()}.${ext}`;const {error}=await getSupabase().storage.from("trade-screenshots").upload(path,file,{contentType:file.type});if(error)throw error;return getSupabase().storage.from("trade-screenshots").getPublicUrl(path).data.publicUrl}
 async function saveTrade(d:TradeDraft,id?:string){if(!session)return;const acc=accounts.find(a=>a.id===d.account_id);const payload={...d,account:acc?.name||d.account||"Personal",user_id:session.user.id,updated_at:new Date().toISOString()};const q=id?getSupabase().from("trades").update(payload).eq("id",id):getSupabase().from("trades").insert(payload);const {error}=await q;if(error)throw error;await load()}
 async function saveAccount(d:AccountDraft,id?:string){if(!session)return;const payload={...d,user_id:session.user.id,updated_at:new Date().toISOString()};const q=id?getSupabase().from("trading_accounts").update(payload).eq("id",id):getSupabase().from("trading_accounts").insert(payload);const {error}=await q;if(error)throw error;await load()}
 async function deleteTrade(id:string){if(!confirm("Delete this trade permanently?"))return;const {error}=await getSupabase().from("trades").delete().eq("id",id);if(error)setError(error.message);else{setSelected(null);load()}}
 async function archiveAccount(a:TradingAccount){if(!confirm(`Archive ${a.name}? Existing trades will stay in your journal.`))return;const {error}=await getSupabase().from("trading_accounts").update({status:"archived",kind:"archived",updated_at:new Date().toISOString()}).eq("id",a.id);if(error)setError(error.message);else load()}
 function toggleTheme(){const n=theme==="light"?"dark":"light";setTheme(n);document.documentElement.dataset.theme=n;localStorage.setItem("tradesea-theme",n)}
 if(loading)return <div className="center-screen">Loading TradeSea…</div>;if(!session)return <AuthScreen/>;
 const title=view[0].toUpperCase()+view.slice(1);
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark small"><Waves size={20}/></span><strong>TradeSea</strong></div><button className="primary sidebar-add" onClick={()=>{setEditingTrade(null);setTradeOpen(true)}}><Plus/>Journal trade</button><nav><Nav active={view==="dashboard"} onClick={()=>setView("dashboard")} icon={<LayoutDashboard/>} label="Dashboard"/><Nav active={view==="journal"} onClick={()=>setView("journal")} icon={<BookOpen/>} label="Journal"/><Nav active={view==="accounts"} onClick={()=>setView("accounts")} icon={<CreditCard/>} label="Accounts"/><Nav active={view==="analytics"} onClick={()=>setView("analytics")} icon={<BarChart3/>} label="Analytics"/><Nav active={view==="settings"} onClick={()=>setView("settings")} icon={<Settings/>} label="Settings"/></nav><div className="sidebar-bottom"><button onClick={toggleTheme}>{theme==="light"?<Moon/>:<Sun/>}{theme==="light"?"Dark mode":"Light mode"}</button><button onClick={()=>getSupabase().auth.signOut()}><LogOut/>Sign out</button></div></aside>
 <main className="main-content"><header className="topbar"><div><p className="eyebrow">Private trading journal</p><h1>{title}</h1><p>{view==="accounts"?"Track live, demo and funded accounts in one place.":"See the habits behind your performance."}</p></div><button className="primary top-add" onClick={()=>{setEditingTrade(null);setTradeOpen(true)}}><Plus/>Journal trade</button></header>{error&&<div className="notice error">{error}<button className="link-button" onClick={()=>setError(null)}>Dismiss</button></div>}
 {view==="dashboard"&&<><Toolbar range={range} preset={preset} from={from} to={to} setFrom={setFrom} setTo={setTo} accounts={accounts} accountFilter={accountFilter} setAccountFilter={setAccountFilter}/><section className="metric-strip"><Metric label="Net P&L" value={money(stats.pnl)} tone={stats.pnl>=0?"positive":"negative"}/><Metric label="Total R" value={`${stats.r>=0?"+":""}${stats.r.toFixed(1)}R`} tone={stats.r>=0?"positive":"negative"}/><Metric label="Win rate" value={`${stats.winRate}%`}/><Metric label="Profit factor" value={stats.profitFactor.toFixed(2)}/></section><section className="dashboard-two"><EquityChart trades={visible}/><WinLoss stats={stats}/></section><section className="dashboard-two"><Rank title="Setup performance" groups={group(visible,"setup")}/><Rank title="Session performance" groups={group(visible,"session")}/></section></>}
 {view==="journal"&&<><div className="journal-toolbar"><div className="search-box"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search trades, setups or notes"/></div><select value={accountFilter} onChange={e=>setAccountFilter(e.target.value)}><option value="all">All accounts</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select value={resultFilter} onChange={e=>setResultFilter(e.target.value)}><option value="all">All results</option><option value="win">Wins</option><option value="loss">Losses</option><option value="breakeven">Breakeven</option></select></div><div className="trade-gallery">{journal.map(t=><TradeCard key={t.id} trade={t} onOpen={()=>setSelected(t)} onEdit={()=>{setEditingTrade(t);setTradeOpen(true)}} onDelete={()=>deleteTrade(t.id)}/>)}</div>{!journal.length&&<Empty onAdd={()=>setTradeOpen(true)}/>}</>}
 {view==="accounts"&&<Accounts accounts={accounts} trades={trades} onAdd={()=>{setEditingAccount(null);setAccountOpen(true)}} onEdit={a=>{setEditingAccount(a);setAccountOpen(true)}} onArchive={archiveAccount} onSelect={id=>{setAccountFilter(id);setView("dashboard")}}/>}
 {view==="analytics"&&<><Toolbar range={range} preset={preset} from={from} to={to} setFrom={setFrom} setTo={setTo} accounts={accounts} accountFilter={accountFilter} setAccountFilter={setAccountFilter}/><section className="analytics-grid"><article className="panel analytics-hero"><p className="eyebrow">Performance summary</p><h2>{stats.pnl>=0?"A profitable period.":"A period worth reviewing."}</h2><p className="muted">{stats.total} trades · {stats.winRate}% win rate · {stats.avgR.toFixed(2)}R average</p><div className="analytics-metrics"><Metric label="Profit factor" value={stats.profitFactor.toFixed(2)}/><Metric label="Average R" value={`${stats.avgR.toFixed(2)}R`}/><Metric label="Plan adherence" value={`${stats.adherence}%`}/></div></article><Rank title="Best setups" groups={group(visible,"setup")}/><Rank title="Best sessions" groups={group(visible,"session")}/></section></>}
 {view==="settings"&&<section className="settings-grid"><article className="panel"><h2>Appearance</h2><p className="muted">Choose the theme you prefer.</p><button className="secondary" onClick={toggleTheme}>{theme==="light"?<Moon/>:<Sun/>}Switch theme</button></article><article className="panel"><h2>Cloud sync</h2><p className="muted">Signed in as {session.user.email}. Trades and accounts sync through Supabase.</p></article></section>}
 </main><nav className="mobile-nav"><button className={view==="dashboard"?"active":""} onClick={()=>setView("dashboard")}><LayoutDashboard/><span>Home</span></button><button className={view==="journal"?"active":""} onClick={()=>setView("journal")}><BookOpen/><span>Journal</span></button><button className="mobile-add" onClick={()=>{setEditingTrade(null);setTradeOpen(true)}}><Plus/></button><button className={view==="accounts"?"active":""} onClick={()=>setView("accounts")}><CreditCard/><span>Accounts</span></button><button className={view==="analytics"?"active":""} onClick={()=>setView("analytics")}><BarChart3/><span>Stats</span></button></nav>
 <TradeModal open={tradeOpen} trade={editingTrade} accounts={accounts.filter(a=>a.status!=="archived")} onClose={()=>setTradeOpen(false)} onSave={saveTrade} onUpload={uploadScreenshot}/><AccountModal open={accountOpen} account={editingAccount} onClose={()=>setAccountOpen(false)} onSave={saveAccount}/>{selected&&<TradeDetail trade={selected} onClose={()=>setSelected(null)} onEdit={()=>{setEditingTrade(selected);setSelected(null);setTradeOpen(true)}} onDelete={()=>deleteTrade(selected.id)}/>}</div>
}
function Nav({active,onClick,icon,label}:{active:boolean;onClick:()=>void;icon:React.ReactNode;label:string}){return <button className={active?"active":""} onClick={onClick}>{icon}{label}</button>}
function Toolbar(p:{range:string;preset:(v:string)=>void;from:string;to:string;setFrom:(v:string)=>void;setTo:(v:string)=>void;accounts:TradingAccount[];accountFilter:string;setAccountFilter:(v:string)=>void}){return <><section className="dashboard-toolbar"><div className="range-tabs">{[["7d","7D"],["30d","30D"],["90d","90D"],["ytd","YTD"],["all","All"],["custom","Custom"]].map(([v,l])=><button key={v} className={p.range===v?"active":""} onClick={()=>p.preset(v)}>{l}</button>)}</div><select className="account-filter" value={p.accountFilter} onChange={e=>p.setAccountFilter(e.target.value)}><option value="all">All accounts</option>{p.accounts.filter(a=>a.status!=="archived").map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></section>{p.range==="custom"&&<section className="custom-range"><label>From<input type="date" value={p.from} onChange={e=>p.setFrom(e.target.value)}/></label><span>to</span><label>To<input type="date" value={p.to} onChange={e=>p.setTo(e.target.value)}/></label></section>}</>}
function Metric({label,value,tone}:{label:string;value:string;tone?:string}){return <article><span>{label}</span><strong className={tone||""}>{value}</strong></article>}
function calcStats(ts:Trade[]){const wins=ts.filter(t=>t.result==="win").length,losses=ts.filter(t=>t.result==="loss").length,pnl=ts.reduce((a,t)=>a+Number(t.pnl||0),0),r=ts.reduce((a,t)=>a+Number(t.r_multiple||0),0),gp=ts.filter(t=>t.pnl>0).reduce((a,t)=>a+Number(t.pnl),0),gl=Math.abs(ts.filter(t=>t.pnl<0).reduce((a,t)=>a+Number(t.pnl),0));return{total:ts.length,wins,losses,bes:ts.length-wins-losses,pnl,r,winRate:ts.length?Math.round(wins/ts.length*100):0,avgR:ts.length?r/ts.length:0,profitFactor:gl?gp/gl:gp?99:0,adherence:ts.length?Math.round(ts.filter(t=>t.followed_plan).length/ts.length*100):0}}
function EquityChart({trades}:{trades:Trade[]}){const points=useMemo(()=>{const sorted=[...trades].sort((a,b)=>`${a.trade_date}T${a.created_at}`.localeCompare(`${b.trade_date}T${b.created_at}`));let total=0;return [{label:"Start",value:0},...sorted.map(t=>({label:new Date(t.trade_date+"T12:00:00").toLocaleDateString("en-GB",{day:"numeric",month:"short"}),value:total+=Number(t.pnl||0)}))]},[trades]);if(points.length<2)return <article className="panel"><div className="card-title"><h2>Equity curve</h2><span>Cumulative P&L</span></div><div className="chart-empty"><TrendingUp/><p>Add trades to build your curve.</p></div></article>;const values=points.map(p=>p.value),min=Math.min(...values,0),max=Math.max(...values,0),span=Math.max(max-min,1),W=800,H=240,pad=24;const xy=points.map((p,i)=>({x:pad+i*(W-pad*2)/Math.max(points.length-1,1),y:pad+(max-p.value)*(H-pad*2)/span,...p}));const path=xy.map((p,i)=>`${i?"L":"M"}${p.x},${p.y}`).join(" ");const zeroY=pad+(max-0)*(H-pad*2)/span;return <article className="panel"><div className="card-title"><h2>Equity curve</h2><span>{money(points.at(-1)?.value||0)}</span></div><div className="equity-chart"><svg viewBox={`0 0 ${W} ${H}`} role="img"><line x1={pad} x2={W-pad} y1={zeroY} y2={zeroY} className="zero-line"/><path d={`${path} L${xy.at(-1)!.x},${H-pad} L${pad},${H-pad} Z`} className="area-path"/><path d={path} className="equity-path"/>{xy.map((p,i)=><g key={i}><circle cx={p.x} cy={p.y} r="4" className="equity-dot"><title>{p.label}: {money(p.value)}</title></circle></g>)}</svg></div><div className="chart-caption"><span>{points[1]?.label}</span><span>{points.at(-1)?.label}</span></div></article>}
function WinLoss({stats}:{stats:ReturnType<typeof calcStats>}){const w=stats.total?stats.wins/stats.total*100:0,l=stats.total?stats.losses/stats.total*100:0;return <article className="panel donut-card"><div className="card-title"><h2>Win / loss</h2><span>{stats.total} trades</span></div><div className="donut" style={{background:`conic-gradient(var(--green) 0 ${w}%,var(--red) ${w}% ${w+l}%,var(--soft) ${w+l}% 100%)`}}><div><strong>{stats.winRate}%</strong><small>WIN RATE</small></div></div><div className="legend"><span><i style={{background:"var(--green)"}}/>Wins {stats.wins}</span><span><i style={{background:"var(--red)"}}/>Losses {stats.losses}</span><span><i style={{background:"var(--muted)"}}/>BE {stats.bes}</span></div></article>}
function group(ts:Trade[],key:"setup"|"session"){const m=new Map<string,{name:string,pnl:number,count:number,r:number}>();for(const t of ts){const n=t[key]||"Unlabelled",v=m.get(n)||{name:n,pnl:0,count:0,r:0};v.pnl+=Number(t.pnl);v.r+=Number(t.r_multiple);v.count++;m.set(n,v)}return [...m.values()].sort((a,b)=>b.pnl-a.pnl)}
function Rank({title,groups}:{title:string;groups:{name:string;pnl:number;count:number;r:number}[]}){return <article className="panel"><div className="card-title"><h2>{title}</h2><span>{groups.length} groups</span></div><div className="rank-list">{groups.slice(0,5).map((g,i)=><div key={g.name}><span className="rank">{i+1}</span><span><b>{g.name}</b><small>{g.count} trades · {g.r.toFixed(1)}R</small></span><strong className={g.pnl>=0?"positive":"negative"}>{money(g.pnl)}</strong></div>)}{!groups.length&&<p className="empty">No data yet.</p>}</div></article>}
function Accounts({accounts,trades,onAdd,onEdit,onArchive,onSelect}:{accounts:TradingAccount[];trades:Trade[];onAdd:()=>void;onEdit:(a:TradingAccount)=>void;onArchive:(a:TradingAccount)=>void;onSelect:(id:string)=>void}){return <><div className="accounts-head"><div><h2>Your trading accounts</h2><p className="muted">Keep live and funded performance separated.</p></div><button className="primary" onClick={onAdd}><Plus/>Add account</button></div><section className="account-grid">{accounts.map(a=>{const at=trades.filter(t=>t.account_id===a.id),pnl=at.reduce((s,t)=>s+Number(t.pnl),0),balance=Number(a.starting_balance)+pnl,days=new Set(at.map(t=>t.trade_date)).size,targetLeft=Math.max(Number(a.profit_target)-pnl,0),maxRoom=Math.max(Number(a.max_drawdown)+Math.min(pnl,0),0);return <article className={`panel account-card status-${a.status}`} key={a.id}><div className="account-card-head"><div><span className="account-kind">{a.kind}</span><h2>{a.name}</h2><p>{a.broker||"No broker set"}</p></div><span className={`status-badge ${a.status}`}>{a.status}</span></div><div className="account-balance"><span>Current balance</span><strong>{money(balance,a.currency)}</strong><small className={pnl>=0?"positive":"negative"}>{pnl>=0?"+":""}{money(pnl,a.currency)} total P&L</small></div><div className="rule-grid"><div><span>Target remaining</span><b>{a.profit_target?money(targetLeft,a.currency):"—"}</b></div><div><span>Drawdown room</span><b>{a.max_drawdown?money(maxRoom,a.currency):"—"}</b></div><div><span>Trading days</span><b>{days}{a.minimum_trading_days?` / ${a.minimum_trading_days}`:""}</b></div><div><span>Trades</span><b>{at.length}</b></div></div><div className="account-actions"><button className="secondary" onClick={()=>onSelect(a.id)}>View stats</button><button className="secondary" onClick={()=>onEdit(a)}><Pencil/>Edit</button>{a.status!=="archived"&&<button className="secondary danger" onClick={()=>onArchive(a)}>Archive</button>}</div></article>})}{!accounts.length&&<article className="panel empty-account"><CreditCard/><h2>Add your first account</h2><p className="muted">Create Vantage Live, funded, challenge or demo accounts.</p><button className="primary" onClick={onAdd}><Plus/>Add account</button></article>}</section></>}
function TradeCard({trade,onOpen,onEdit,onDelete}:{trade:Trade;onOpen:()=>void;onEdit:()=>void;onDelete:()=>void}){return <article className="trade-card" onClick={onOpen}>{trade.screenshot_url?<img src={trade.screenshot_url} alt="Trade chart"/>:<div className="chart-placeholder"><TrendingUp/></div>}<div className="trade-card-body"><div className="trade-card-top"><div><small>{trade.trade_date} · {trade.account}</small><h2>{trade.instrument}</h2></div><span className={`result-pill ${trade.result}`}>{trade.result}</span></div><div className="trade-card-values"><span><small>P&L</small><b className={trade.pnl>=0?"positive":"negative"}>{money(trade.pnl)}</b></span><span><small>Result</small><b>{Number(trade.r_multiple).toFixed(1)}R</b></span><span><small>Direction</small><b>{trade.direction}</b></span></div><div className="tag-row">{[trade.setup,trade.session,trade.emotion].filter(Boolean).map(v=><span key={v}>{v}</span>)}</div><div className="card-actions"><button onClick={e=>{e.stopPropagation();onEdit()}}><Pencil/>Edit</button><button className="danger" onClick={e=>{e.stopPropagation();onDelete()}}><Trash2/>Delete</button></div></div></article>}
function Empty({onAdd}:{onAdd:()=>void}){return <section className="panel empty-journal"><BookOpen/><h2>Your journal is ready</h2><p>Add your first trade.</p><button className="primary" onClick={onAdd}><Plus/>Journal trade</button></section>}
function TradeDetail({trade,onClose,onEdit,onDelete}:{trade:Trade;onClose:()=>void;onEdit:()=>void;onDelete:()=>void}){return <div className="detail-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><article className="trade-detail"><button className="icon-btn detail-close" onClick={onClose}><X/></button>{trade.screenshot_url?<img className="detail-chart" src={trade.screenshot_url} alt="Trade chart"/>:<div className="detail-chart placeholder"><TrendingUp/></div>}<div className="detail-content"><p className="eyebrow">{trade.trade_date} · {trade.account}</p><div className="detail-title"><h2>{trade.instrument}</h2><span className={`result-pill ${trade.result}`}>{trade.result}</span></div><div className="detail-stats"><Metric label="P&L" value={money(trade.pnl)} tone={trade.pnl>=0?"positive":"negative"}/><Metric label="R result" value={`${Number(trade.r_multiple).toFixed(1)}R`}/><Metric label="Direction" value={trade.direction}/><Metric label="Plan" value={trade.followed_plan?"Followed":"Broken"}/></div>{trade.notes&&<div className="notes-box"><span>Journal notes</span><p>{trade.notes}</p></div>}<div className="detail-actions"><button className="secondary" onClick={onEdit}><Pencil/>Edit</button><button className="secondary danger" onClick={onDelete}><Trash2/>Delete</button></div></div></article></div>}
