"use client";
import {useEffect,useState} from "react";
import {X} from "lucide-react";
import type {DailyReview,DailyReviewDraft,TradingAccount} from "@/lib/types";

const today=()=>new Date().toISOString().slice(0,10);
const blank=(date=today(),accountId:string|null=null):DailyReviewDraft=>({account_id:accountId,review_date:date,mood:3,focus:3,discipline:3,sleep_quality:3,what_went_well:"",what_to_improve:"",next_session_focus:""});

export function ReviewModal({open,review,date,accountId,accounts,onClose,onSave}:{open:boolean;review:DailyReview|null;date:string;accountId:string|null;accounts:TradingAccount[];onClose:()=>void;onSave:(draft:DailyReviewDraft,id?:string)=>Promise<void>}){
 const [draft,setDraft]=useState<DailyReviewDraft>(blank(date,accountId)),[saving,setSaving]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!open)return;setError("");setDraft(review?{account_id:review.account_id,review_date:review.review_date,mood:review.mood,focus:review.focus,discipline:review.discipline,sleep_quality:review.sleep_quality,what_went_well:review.what_went_well,what_to_improve:review.what_to_improve,next_session_focus:review.next_session_focus}:blank(date,accountId))},[open,review,date,accountId]);
 if(!open)return null;
 const set=<K extends keyof DailyReviewDraft>(key:K,value:DailyReviewDraft[K])=>setDraft(v=>({...v,[key]:value}));
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");try{await onSave(draft,review?.id);onClose()}catch(err){setError(err instanceof Error?err.message:"Could not save review")}finally{setSaving(false)}}
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form className="trade-sheet review-sheet" onSubmit={submit}><div className="sheet-grabber"/><div className="modal-head"><div><p className="eyebrow">Session reflection</p><h2>{review?"Edit daily review":"Daily review"}</h2></div><button type="button" className="icon-btn" onClick={onClose}><X/></button></div>{error&&<div className="notice error">{error}</div>}<div className="review-top-grid"><label>Date<input type="date" value={draft.review_date} onChange={e=>set("review_date",e.target.value)} required/></label><label>Account<select value={draft.account_id||""} onChange={e=>set("account_id",e.target.value||null)}><option value="">All / general review</option>{accounts.filter(a=>a.status!=="archived").map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label></div><div className="score-grid"><Score label="Mood" value={draft.mood} onChange={v=>set("mood",v)}/><Score label="Focus" value={draft.focus} onChange={v=>set("focus",v)}/><Score label="Discipline" value={draft.discipline} onChange={v=>set("discipline",v)}/><Score label="Sleep" value={draft.sleep_quality} onChange={v=>set("sleep_quality",v)}/></div><label>What went well<textarea rows={3} value={draft.what_went_well} onChange={e=>set("what_went_well",e.target.value)} placeholder="What did you execute well today?"/></label><label>What needs improving<textarea rows={3} value={draft.what_to_improve} onChange={e=>set("what_to_improve",e.target.value)} placeholder="What mistake or habit needs attention?"/></label><label>Focus for the next session<textarea rows={2} value={draft.next_session_focus} onChange={e=>set("next_session_focus",e.target.value)} placeholder="One clear action for your next session"/></label><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving?"Saving…":"Save review"}</button></div></form></div>
}

function Score({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <div className="score-control"><span>{label}</span><div>{[1,2,3,4,5].map(n=><button type="button" key={n} className={value===n?"active":""} onClick={()=>onChange(n)}>{n}</button>)}</div></div>}
